escuela_online/frontend/urls.py
from django.urls import path
from escuela_online.frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.index, name='index'),
    path('curso/<slug:slug_curso>', views.descripcion_curso, name='descripcion_curso'),
    path('checkout/<slug:slug_curso>', views.checkout, name='checkout'),
    path('perfil/usuario/<int:id_usuario>', views.perfil_usuario, name='perfil_usuario'),
    path('registro', views.registro_usuario, name='registro_usuario'),
    path('usuario/mis-cursos', views.mis_cursos, name='mis_cursos'),
    path('modulo/<slug:slug_modulo>', views.listado_clases, name='listado_clases'),
    path('cursos/<slug:slug_categoria>', views.listado_cursos, name='listado_cursos'),
    path('categorias', views.listado_categorias, name='listado_categorias'),
    path('detalle/clase/<slug:slug_clase>', views.detalle_clase, name='detalle_clase'),
    # path('comprar/curso/resumen/$', views.comprar_curso, name='comprar_curso'),
    path('crear/pago/curso/<slug:slug_curso>', views.crear_pago, name='crear_pago'),
    path('ejecutar/pago/curso/<slug:slug_curso>', views.ejecutar_pago, name='ejecutar_pago'),
    # path('respuesta/pago/curso/$', views.respuesta_pago_curso, name='respuesta_pago_curso'),
    # path('pago/curso/tarjeta$', views.crear_pago_tarjeta, name='crear_pago_tarjeta'),

]

escuela_online/urls.py
"""escuela_online_web URL Configuration
"""
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('escuela_online.frontend.urls', namespace="frontend")),
    path('accounts/', include('django.contrib.auth.urls')),
]

escuela_online/backend/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Transpose
from escuela_online.utils import PathAndRename
from django.contrib.auth.models import AbstractUser, UserManager
from django.template.defaultfilters import slugify

import binascii
import os

path_and_rename_imagen_curso = PathAndRename("cursos")
path_and_rename_imagen_usuario = PathAndRename("usuario")
app_label = 'backend'
# Create your models here.

ESTADOS_CURSO = (
    (0, 'abierto'),
    (1, 'pausa'),
    (2, 'cerrado'),
)

MONEDAS = (
    (0, 'MXN'),
    (1, 'USD'),
    (2, 'EUR'),
)

TIPO_DURACION = (
    (0, 'HORAS'),
    (1, 'DIAS'),
    (2, 'SEMANAS'),
    (3, 'MESES'),
)

TIPO_RECURSO = (
    (0, 'PDF'),
    (1, 'PPT'),
    (2, 'DOC'),
    (3, 'VIDEO'),
)


class Usuario(AbstractUser):
    objects = UserManager()
    telefono = models.IntegerField(blank=True, null=True)
    avatar = ProcessedImageField(max_length=255, blank=True, null=True,
                             upload_to=path_and_rename_imagen_usuario,
                             processors=[Transpose()])
    class Meta:
        app_label = 'backend'


class Token(models.Model):
    key = models.CharField(max_length=40, primary_key=True)
    user = models.OneToOneField(Usuario, related_name='auth_token', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = 'backend'

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super(Token, self).save(*args, **kwargs)

    @staticmethod
    def generate_key():
        return binascii.hexlify(os.urandom(20)).decode()

    def __str__(self):
        return self.key


class Curso(models.Model):
    titulo = models.CharField(max_length=300)
    categoria = models.ForeignKey('Categoria', related_name='cursos', on_delete=models.PROTECT)
    estado = models.IntegerField(default=0, choices=ESTADOS_CURSO)
    imagen_principal = ProcessedImageField(max_length=255, blank=True, null=True,
                                 upload_to=path_and_rename_imagen_curso,
                                 processors=[Transpose()])
    descripcion = models.TextField()
    video = models.CharField(max_length=255, blank=True, null=True)
    precio = models.IntegerField(default=0)
    moneda = models.IntegerField(default=0, choices=MONEDAS)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_inicio = models.DateTimeField(null=True, blank=True)
    tiempo_duracion = models.ForeignKey('TiempoDuracion', null=True, blank=True, on_delete=models.PROTECT)
    profesor = models.ManyToManyField('Profesor', related_name='cursos')
    estudiantes = models.ManyToManyField('Estudiante', related_name='cursos', blank=True)
    premium = models.BooleanField(blank=True, default=0)
    slug = models.SlugField(max_length=200, editable=False, unique=True)
    class Meta:
        app_label = 'backend'
    def __str__(self):
        return "{}-{}".format(self.titulo, self.categoria)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.titulo)
        return super(Curso, self).save(*args, **kwargs)


class Modulo(models.Model):
    nombre = models.CharField(max_length=300)
    curso = models.ForeignKey('Curso', related_name='modulos', on_delete=models.PROTECT)
    descripcion = models.TextField(null=True, blank=True)
    video = models.CharField(max_length=255, blank=True, null=True)
    tiempo_duracion = models.ForeignKey('TiempoDuracion', null=True, blank=True, on_delete=models.PROTECT)
    slug = models.SlugField(max_length=200, editable=False, null=True, blank=True)
    class Meta:
        app_label = 'backend'
    def __str__(self):
        return "{}-{}".format(self.nombre, self.curso)

    def get_duracion(self):
        return self.tiempo_duracion

    def get_cantidad_clases(self):
        return self.clases.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        return super(Modulo, self).save(*args, **kwargs)


class Clase(models.Model):
    nombre = models.CharField(max_length=300)
    modulo = models.ForeignKey('Modulo', related_name='clases', null=True, blank=True, on_delete=models.PROTECT)
    descripcion = models.TextField()
    tiempo_duracion = models.FloatField(default=0.0, help_text='en horas')
    es_gratis = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, editable=False, null=True, blank=True)
    class Meta:
        app_label = 'backend'
    def __str__(self):
        return "{}-{}".format(self.modulo, self.nombre)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        return super(Clase, self).save(*args, **kwargs)

class Recursos(models.Model):
    titulo = models.CharField(max_length=300)
    enlace = models.CharField(max_length=300, null=True, blank=True)
    archivo = models.FileField(null=True, blank=True)
    tipo = models.IntegerField(default=0, choices=TIPO_RECURSO)
    clase = models.ForeignKey('Clase', related_name='recursos', on_delete=models.PROTECT)
    class Meta:
        app_label = 'backend'
    def __str__(self):
        return "{}-{}".format(self.titulo, self.tipo)


class Profesor(models.Model):
    usuario = models.ForeignKey('Usuario', related_name='profesores', on_delete=models.PROTECT)
    descripcion = models.TextField(max_length=3000, blank=True, null=True)
    estudios_cursados = models.CharField(max_length=300, blank=True, null=True)

    def __str__(self):
        return "{}.{}".format(self.estudios_cursados, self.usuario.first_name)

    class Meta:
        app_label = 'backend'

class Contacto(models.Model):
    telefono = models.CharField(max_length=12)
    email = models.CharField(max_length=30, null=True, blank=True)
    web = models.CharField(max_length=30, null=True, blank=True)
    facebook = models.CharField(max_length=30, null=True, blank=True)
    twitter = models.CharField(max_length=30, null=True, blank=True)
    instagram = models.CharField(max_length=30, null=True, blank=True)
    youtube = models.CharField(max_length=30, null=True, blank=True)
    profesor = models.ForeignKey('Profesor', related_name='contacto', on_delete=models.PROTECT)
    class Meta:
        app_label = 'backend'
    def __str__(self):
        return "{}-{}".format(self.musico,self.telefono)


class Estudiante(models.Model):
    usuario = models.ForeignKey('Usuario', related_name='estudiante', on_delete=models.PROTECT)
    class Meta:
        app_label = 'backend'
    def __str__(self):
        return self.usuario.get_full_name()


class Categoria(models.Model):
    nombre = models.CharField(max_length=300)
    descripcion = models.TextField()
    slug = models.SlugField(max_length=200,null=True, editable=False, unique=True)
    class Meta:
        app_label = 'backend'
    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        self.slug = slugify(self.nombre)
        return super(Categoria, self).save(*args, **kwargs)


class TiempoDuracion(models.Model):
    cantidad = models.IntegerField(default=0)
    tipo = models.IntegerField(default=0, choices=TIPO_DURACION)
    class Meta:
        app_label = 'backend'
    def __str__(self):
        return "{}{}".format(self.cantidad, self.get_tipo_display())

escuela_online/frontend/models.py
from django.db import models

# Create your models here.

escuela_online/frontend/forms.py
from escuela_online.backend.models import Usuario
from django import forms
from django.forms import ModelForm

MES = (
    ('01','01'),
    ('02','02'),
    ('03','03'),
    ('04','04'),
    ('05','05'),
    ('06','06'),
    ('07','07'),
    ('08','08'),
    ('09','09'),
    ('10','10'),
    ('11','11'),
    ('12','12'),
)
ANNO = (
    ('2017','2017'),
    ('2018','2018'),
    ('2019','2019'),
    ('2020','2020'),
    ('2021','2021'),
    ('2022','2022'),
    ('2023','2023'),
    ('2025','2025'),
    ('2025','2025'),
)

class UsuarioForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'E-mail'}), required=True)
    username = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Confirmar E-mail'}), required=True)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña'}), required=True)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirmar contraseña'}), required=True)


class PerfilUsuario(ModelForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'last_name', 'avatar']


class PagoCursoTarjetaForm(forms.Form):
    nombre = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nombre'}), required=True)
    apellido = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Apellido'}), required=True)
    numero = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Número de tarjeta'}), required=True)
    mes = forms.ChoiceField(choices=MES, required=True)
    anno = forms.ChoiceField(choices=ANNO, required=True)
    cvv = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'CVV'}), required=True)

escuela_online/frontend/templates/frontend/checkout.html
{% extends 'frontend/base.html' %}
{% load staticfiles %}
{% block custom_assets %}
    <script src="https://www.paypalobjects.com/api/checkout.js"></script>
    <script>
        var CREATE_PAYMENT_URL = 'http://localhost:8000/crear/pago/curso/{{ curso.slug }}';
        var EXECUTE_PAYMENT_URL = 'http://localhost:8000/ejecutar/pago/curso/{{ curso.slug }}';

        paypal.Button.render({

            env: 'sandbox', // Or 'sandbox'

            commit: true, // Show a 'Pay Now' button

            payment: function () {
                return paypal.request.post(CREATE_PAYMENT_URL).then(function (data) {
                    return data.id;
                });
            },

            onAuthorize: function (data) {
                return paypal.request.post(EXECUTE_PAYMENT_URL, {
                    paymentID: data.paymentID,
                    payerID: data.payerID
                }).then(function (response) {
                    alert(response.msg);
                });
            }

        }, '#paypal-button');
    </script>
{% endblock %}
{% block container %}
    <div class="container">
        <div class="col-right">

            {% if curso !=  None %}
                <div class="strip-lessons">
                    <div class="row">
                        <p class="alert alert-info"><i class="icon-info-sign icon-2x"></i> <b>Información: </b>Usted
                            está a punto de comprar el siguiente curso:</p>
                        <div class="col-md-3 col-xs-6">
                            <div class="box-style-one borders"><img
                                    src="{% static 'frontend/img/lessons.png' %}" alt="">
                                <h5>{{ curso.categoria }}</h5>
                            </div>
                        </div>
                        <div class="clearfix visible-xs-block"></div>
                        <div class="col-md-9">
                            <h4>
                                <a href="{% url 'frontend:descripcion_curso' slug_curso=curso.slug %}">{{ curso.titulo }}</a>
                            </h4>
                            <p>
                                {{ curso.descripcion|truncatechars:'250' }}
                            </p>
                            <ul class="data-lessons">
                                {#                                        <li>#}
                                {#                                            <i class="icon-time"></i>Duración:#}
                                {#                                            <b>{{ curso.tiempo_duracion.cantidad }} {{ curso.tiempo_duracion.get_tipo_display }}</b>#}
                                {#                                        </li>#}
                                <li>
                                    Profesor:
                                    {% for profesor in curso.profesor.all %}
                                        <b>{{ profesor }}</b>
                                    {% endfor %}

                                </li>
                                <li>
                                    <i class="icon-film"></i>
                                    <a class="fancybox-media button_red_medium"
                                       href="{% url 'frontend:descripcion_curso' slug_curso=curso.slug %}">

                                        Ver curso</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <h3 class="alert-success text-center">Precio:
                        <b>${{ curso.precio }} {{ curso.get_moneda_display }}</b></h3>
                    {% if user.is_authenticated %}
                        <div class="row">
                            <h5 class="text-center text-info">Puede realizar el pago con su cuenta de PayPal o con su
                                tarjeta de crédito o débito</h5>
                            <div class="col-sm-6">
                                {#                                <a href="{% url 'frontend:crear_pago' slug_curso=curso.slug %}">Pagar con paypal</a>#}
                                <div id="paypal-button"></div>
                            </div>

                        </div>
                    {% else %}
                        <p class="alert alert-danger">Debe estar registrado en el sitio para poder comprar este
                            curso</p>
                        <a class="button_medium" href="{% url 'auth_login' %}">Accerder</a>
                        <a class="button_red_medium" href="{% url 'registration_register' %}">Registrarse</a>
                    {% endif %}
                </div><!-- End Strip course -->

            {% else %}
                <h1 class="alert alert-warning">{{ msg }} </h1>
                <p class="alert alert-info">Puede ver todos sus cursos en <a href="{% url 'frontend:mis_cursos' %}">MIS CURSOS</a></p>
            {% endif %}
        </div>
    </div>

{% endblock %}

escuela_online/frontend/templates/frontend/descripcion_curso.html
{% extends 'frontend/base.html' %}
{% load staticfiles %}
{% block container %}
    <div class="container">
        {% if curso != None %}
            <div class="row">
                <div class="col-md-12">
                    <h1>{{ curso.titulo }}</h1>
                    <ul class="breadcrumb">
                        <li><a href=" {% url 'frontend:index' %}">Inicio</a> <span class="divider"></span></li>
                        <li class="active">{{ curso.categoria }}</li>
                    </ul>
                </div>

                <!-- =========================Start Col left section ============================= -->
                <aside class="col-md-4 col-sm-4">
                    <div class="col-left">
                        <h3>Categorías de cursos</h3>
                        <hr>
                        <ul class="submenu-col">
                            <li><a href="{% url 'frontend:listado_categorias' %}">Todas las catgorías</a></li>
                            {% for categoria in categorias %}
                                <li><a href="{% url 'frontend:listado_cursos' slug_categoria=categoria.slug %}"
                                >{{ categoria }}
                                    ({{ categoria.cursos.all|length }})</a></li>
                            {% endfor %}
                        </ul>
                        <hr>
                        <p><a href="#" class=" button_red_small">Próximos cursos</a></p>

                    </div>
                    <p><img src="{% static 'frontend/img/banner.jpg' %}" alt="Banner"
                            class="img-rounded img-responsive"></p>
                </aside>

                <!-- =========================Start Col right section ============================= -->
                <section class="col-md-8 col-sm-8">
                    <div class="col-right">
                        {% if curso.video %}
                            <iframe width="420" height="315"
                                    src="https://www.youtube.com/embed/{{ curso.video }}?autoplay=0">
                            </iframe>
                        {% endif %}

                        {#                        <div class="main-img">#}
                        {#                            <img src="{% static 'frontend/img/pic-4.jpg' %}" alt="" class="img-responsive">#}
                        {#                            <p class="lead">Tibique dolores adversarium ne vel. At vide errem duo, vis luptatum menandri#}
                        {#                                ullamcorper id. </p>#}
                        {#                        </div>#}
                        <h2>Módulos del curso</h2>
                        <hr>
                        {% if modulos|length > 0 %}
                            {% for modulo in modulos %}

                                <div class="strip-courses">
                                    <div class="title-course">
                                        <h3>{{ modulo.nombre }}
                                        </h3>
                                        <ul>
                                            <li><i class="icon-bookmark"></i> ID: 012</li>
                                        </ul>
                                    </div>
                                    <div class="description">
                                        <p>{{ modulo.descripcion|truncatechars:'350' }}</p>
                                        <ul>
                                            <li><i class="icon-book"></i> {{ modulo.get_cantidad_clases }} clases</li>
                                            <li><i class="icon-reorder"></i> {{ modulo.get_duracion }}</li>
                                        </ul>
                                        <a href="{% url 'frontend:listado_clases' slug_modulo=modulo.slug %}"
                                           class="button_medium button-align-2">Ver clases </a>
                                    </div>
                                </div><!-- end strip-->

                            {% endfor %}
                        {% else %}
                            <div class="alert-danger"><h3>Este curso no cuenta con módulos activos todavía.</h3></div>
                        {% endif %}
                        {% if not tiene_curso %}
                            <p class="text-center"><a href="{% url 'frontend:checkout' slug_curso=curso.slug %}"
                                                      class="button_large">Comprar curso
                                ${{ curso.precio }} {{ curso.get_moneda_display }}</a></p>
                        {% endif %}
                        {# Si se va a incluir la tabla para los webinars revisr rl template para el diseño #}
                    </div><!-- end col right-->
                </section>
            </div><!-- end row-->
        {% else %}
            <h1>Lo sentimos el curso que busca ya no está disponible.</h1>
        {% endif %}

    </div> <!-- end container-->
{% endblock %}

escuela_online/frontend/templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load staticfiles %}
{% block custom_assets %}
    <link rel="stylesheet" type="text/css" href="{% static 'frontend/js/slick/slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'frontend/js/slick/slick/slick-theme.css' %}"/>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="{% static 'frontend/js/slick/slick/slick.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('.slider').slick({
                infinite: true,
                slidesToShow: 1,
                autoplay: true,
                autoplaySpeed: 2000
            });

        });
    </script>

{% endblock %}
{% block container %}

    <!--Star slider-->
    <section class="slider">
        <img src="{% static 'frontend/images/slides/slider1.jpg' %}" alt="imagen1">
        <img src="{% static 'frontend/images/slides/slider2.jpg' %}" alt="imagen2">
    </section><!--End slider-->


    <div class="container">

        <div class="row" id="main-boxes">
            <div class="col-md-4 col-sm-4">
                <div class="box-style-2 green">
                    <a href="{% url 'frontend:listado_categorias' %}" title="Todos los cursos">
                        <img src="{% static 'frontend/img/icon-home-course.png' %}" alt="">
                        <h3>Cursos</h3>
                        <p>Aquí podrá ver todos los cursos que impartimos agrupados por categoría de contenidos</p>
                    </a>
                </div>
            </div>

            <div class="col-md-4 col-sm-4">
                <div class="box-style-2 orange">
                    <a href="" title="Registro">
                        <img src="{% static 'frontend/img/icon-home-apply.png' %}" alt="">
                        <h3>Regístrate</h3>
                        <p>Le tomará menos de 1 minuto registrarse y acceder a todo nuestro catálogo de cursos y
                            noticias. </p>
                    </a>
                </div>
            </div>

            <div class="col-md-4 col-sm-4">
                <div class="box-style-2 red">
                    <a href="contact.html" title="Plan a visit">
                        <img src="{% static 'frontend/img/icon-home-visit.png' %}" alt="">
                        <h3>Contáctanos</h3>
                        <p>Cualquier duda, sugerencia o aspecto que usted crea debamos saber. Contáctenos estamos a sus
                            órdenes</p>
                    </a>
                </div>
            </div>
        </div>
    </div> <!-- end container-->


    <div class="container">
        <div class="row">
            <aside class="col-sm-3 col-xs-12">
                <div class="col-left">
                    <h3>Categorías de cursos</h3>
                    <hr>
                    <ul class="submenu-col">
                        <li><a href="{% url 'frontend:listado_categorias' %}">Todas las catgorias</a></li>
                        {% for categoria in categorias %}
                            <li><a href="{% url 'frontend:listado_cursos' slug_categoria=categoria.slug %}"
                            >{{ categoria }}
                                ({{ categoria.cursos.all|length }})</a></li>
                        {% endfor %}
                    </ul>
                    <hr>
                    <p><a href="#" class=" button_red_small">Próximos cursos</a></p>

                </div>
                    {% include 'frontend/includes/block_login.html' %}
            </aside>

            <section class="col-sm-9 col-xs-12">
                <div class="col-right">
                    <h2>Cursos más recientes</h2>
                    <hr>
                    {% for curso in cursos_premium %}

                        {% include 'frontend/item_curso.html' %}

                    {% endfor %}

                    <p class="text-center"><a href="{% url 'frontend:listado_categorias' %}" class="button_large">Ver
                        todos los cursos
                    </a></p>

                </div>
            </section>
        </div>
    </div><!-- end container-->

{% endblock %}

escuela_online/frontend/templates/frontend/item_curso.html
{% load staticfiles %}
<div class="strip-lessons">
    <div class="row">
        <div class="col-sm-3 col-xs-4">
            <div class="box-style-one borders"><img
                    src="{% static 'frontend/img/lessons.png' %}" alt="" width="80">
                <h5>{{ curso.categoria }}</h5>
            </div>
        </div>
        <div class="clearfix visible-xs-block"></div>
        <div class="col-sm-9 col-xs-8">
            <h4>
                <a href="{% url 'frontend:descripcion_curso' slug_curso=curso.slug %}">{{ curso.titulo }}</a>
            </h4>
            <p>
                {{ curso.descripcion|truncatechars:'250' }}
            </p>
            <ul class="data-lessons">
                <li>
                    Profesor:
                    {% for profesor in curso.profesor.all %}
                        <b>{{ profesor }}</b>
                    {% endfor %}

                </li>

                <li>Precio: <b>${{ curso.precio }} {{ curso.get_moneda_display }}</b></li>
                {% if not perfil %}
                    <li>
                        <a
                                href="{% url 'frontend:checkout' slug_curso=curso.slug %}"
                                class="button_red_medium">
                            Comprar</a>
                    </li>
                {% endif %}

                <li>
                    <i class="icon-film"></i>
                    <a class="fancybox-media"
                       href="{% url 'frontend:descripcion_curso' slug_curso=curso.slug %}">

                        Ver curso</a>
                </li>
            </ul>
        </div>
    </div>
</div><!-- End Strip course -->

escuela_online/frontend/templates/frontend/listado_clases.html
{% extends 'frontend/base.html' %}
{% load staticfiles %}
{% block container %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{ curso.categoria }}</h1>
                <ul class="breadcrumb">
                    <li><a href=" {% url 'frontend:index' %}">Inicio</a> <span class="divider"></span></li>
                    <li>
                        <a href=" {% url 'frontend:descripcion_curso' slug_curso=modulo.curso.slug %}">{{ modulo.curso }}</a>
                        <span class="divider"></span></li>
                    <li class="active">{{ modulo.nombre }}</li>
                </ul>
            </div>

            <!-- =========================Start Col left section ============================= -->
            <aside class="col-sm-3 col-xs-12">
                <div class="col-left">
                    <h3>Módulos de cursos</h3>
                    <hr>
                    <ul class="submenu-col">
                        {% for modulo in modulo.curso.modulos.all %}
                            <li><a href="{% url 'frontend:listado_clases' slug_modulo=modulo.slug %}"
                            >{{ modulo.nombre }}
                                ({{ modulo.clases.all|length }})</a></li>
                        {% endfor %}
                    </ul>
                    <hr>
                    <p><a href="#" class=" button_red_small">Próximos cursos</a></p>

                </div>
                {% include 'frontend/includes/block_login.html' %}

            </aside>

            <!-- =========================Start Col right section ============================= -->
            <section class="col-sm-9 col-xs-12">
                <div class="col-right">
                    <div class="main-img">
                        <h2 class="text-center">Módulo: {{ modulo.nombre }}</h2>
                    </div>

                    {% for clase in clases %}


                        <div class="strip-lessons">
                            <div class="row">
                                <div class="col-md-3 col-sm-6 col-xs-6">
                                    <div class="box-style-one borders"><img
                                            src="{% static 'frontend/img/lessons.png' %}" alt="LESSON_ICON" width="80">
                                        <h5>
                                            clase: {{ forloop.counter }}</h5>
                                    </div>
                                </div>
                                <div class="clearfix visible-xs-block"></div>
                                <div class="col-md-9 col-sm-12">
                                    <h4>{{ clase.nombre }}</h4>
                                    <p>{{ clase.descripcion|truncatechars:'250' }} </p>
                                    <ul class="data-lessons">
                                        <li><i class="icon-time"></i>Duración: {{ clase.tiempo_duracion }}hr</li>
                                        <li><i class="icon-film"></i>
                                            {% if tiene_curso %}
                                                <li>
                                                    <i class="icon-cloud-download"></i>
                                                    <a href="{% url 'frontend:detalle_clase' slug_clase=clase.slug %}">
                                                        Ver clase completa</a>
                                                </li>
                                            {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div><!-- End Strip course -->
                        {% if not tiene_curso %}

                            <p class="text-center"><a href="{% url 'frontend:checkout' slug_curso=curso.slug %}"
                                                      class="button_large">Comprar curso
                                ${{ curso.precio }} {{ curso.get_moneda_display }}</a></p>
                        {% endif %}

                    {% endfor %}

                    <div class="widget borders widget-table">

                        <div class="widget-header">
                            <h5>Si se van a dar clases presenciales o webinars planificación</h5>
                        </div> <!-- .widget-header -->
                    </div> <!-- /widget -->
                </div><!-- end col right-->
            </section>
        </div><!-- end row-->

    </div> <!-- end container-->
{% endblock %}